import { useMemo, useState } from "react";

// Local-only fixture. Every entity, identifier, timestamp, and result is fictional.
export const SYNTHETIC_STATE = {
  dataOrigin: "synthetic",
  actors: [
    { id: "Actor_Synthetic_001", persona: "Persona_Synthetic_001", handles: ["northstar_mock", "ns_listing"], pgp: "PGP_MOCK_001", wallet: "0x000000000000000000000000000000000000mock1", platforms: ["Forum_A", "Market_A"], tone: "consistent" },
    { id: "Actor_Synthetic_002", persona: "Persona_Synthetic_002", handles: ["northstar_alt"], pgp: "PGP_MOCK_001", wallet: "0x000000000000000000000000000000000000mock1", platforms: ["Market_B"], tone: "decoy" },
    { id: "Actor_Synthetic_003", persona: "Persona_Synthetic_003", handles: ["harbor_mock"], pgp: "PGP_MOCK_003", wallet: "0x000000000000000000000000000000000000mock3", platforms: ["Forum_C"], tone: "distinct" },
    { id: "Actor_Synthetic_004", persona: "Persona_Synthetic_004", handles: ["cedar_mock"], pgp: "PGP_MOCK_004", wallet: "0x000000000000000000000000000000000000mock4", platforms: ["Forum_D", "Market_C"], tone: "consistent" },
    { id: "Actor_Synthetic_005", persona: "Persona_Synthetic_005", handles: ["delta_mock"], pgp: "PGP_MOCK_005", wallet: "0x000000000000000000000000000000000000mock5", platforms: ["Market_D"], tone: "uncertain" },
    { id: "Actor_Synthetic_006", persona: "Persona_Synthetic_006", handles: ["ember_mock"], pgp: "PGP_MOCK_006", wallet: "0x000000000000000000000000000000000000mock6", platforms: ["Forum_E"], tone: "distinct" },
    { id: "Actor_Synthetic_007", persona: "Persona_Synthetic_007", handles: ["fir_mock"], pgp: "PGP_MOCK_007", wallet: "0x000000000000000000000000000000000000mock7", platforms: ["Market_E"], tone: "consistent" },
    { id: "Actor_Synthetic_008", persona: "Persona_Synthetic_008", handles: ["grove_mock"], pgp: "PGP_MOCK_008", wallet: "0x000000000000000000000000000000000000mock8", platforms: ["Forum_F", "Market_F"], tone: "decoy" },
    { id: "Actor_Synthetic_009", persona: "Persona_Synthetic_009", handles: ["horizon_mock"], pgp: "PGP_MOCK_009", wallet: "0x000000000000000000000000000000000000mock9", platforms: ["Forum_G"], tone: "uncertain" },
    { id: "Actor_Synthetic_010", persona: "Persona_Synthetic_010", handles: ["island_mock"], pgp: "PGP_MOCK_010", wallet: "0x000000000000000000000000000000000000mock10", platforms: ["Market_G"], tone: "consistent" },
    { id: "Actor_Synthetic_011", persona: "Persona_Synthetic_011", handles: ["juniper_mock"], pgp: "PGP_MOCK_011", wallet: "0x000000000000000000000000000000000000mock11", platforms: ["Forum_H"], tone: "distinct" },
    { id: "Actor_Synthetic_012", persona: "Persona_Synthetic_012", handles: ["keystone_mock"], pgp: "PGP_MOCK_012", wallet: "0x000000000000000000000000000000000000mock12", platforms: ["Market_H", "Forum_I"], tone: "uncertain" },
  ],
  evidence: [
    { id: "Evidence_Mock_001", kind: "Stylometry", source: "Source_Mock_Alpha", group: "independent-writing", strength: 0.91, supports: "Actor_Synthetic_001", status: "supporting", note: "Vocabulary and sentence rhythm overlap." },
    { id: "Evidence_Mock_002", kind: "PGP relationship", source: "Source_Mock_Beta", group: "identity-key", strength: 0.88, supports: "Actor_Synthetic_001", status: "supporting", note: "Shared fictional PGP identifier." },
    { id: "Evidence_Mock_003", kind: "Wallet relationship", source: "Source_Mock_Beta", group: "wallet-cluster", strength: 0.72, supports: "Actor_Synthetic_002", status: "supporting", note: "Repeated synthetic transaction pattern." },
    { id: "Evidence_Mock_004", kind: "Behavior", source: "Source_Mock_Gamma", group: "behavior-window", strength: 0.84, supports: "Actor_Synthetic_001", status: "supporting", note: "Overlapping fictional active hours." },
    { id: "Evidence_Mock_005", kind: "Timestamp conflict", source: "Source_Mock_Delta", group: "timeline-conflict", strength: 0.63, supports: "Actor_Synthetic_001", status: "conflicting", note: "Synthetic timestamps cannot be reconciled." },
    { id: "Evidence_Mock_006", kind: "Infrastructure", source: "Source_Mock_Epsilon", group: "shared-infra", strength: 0.56, supports: "Actor_Synthetic_002", status: "redundant", note: "Same mock server fingerprint as another record." },
  ],
  sources: [
    { id: "Source_Mock_Alpha", lineage: "Synthetic writing fixture", reliability: 0.93, errorRate: 0.04, independence: "independent" },
    { id: "Source_Mock_Beta", lineage: "Synthetic identifier fixture", reliability: 0.81, errorRate: 0.11, independence: "dependent" },
    { id: "Source_Mock_Gamma", lineage: "Synthetic behavior fixture", reliability: 0.86, errorRate: 0.08, independence: "independent" },
    { id: "Source_Mock_Delta", lineage: "Synthetic timeline fixture", reliability: 0.61, errorRate: 0.22, independence: "independent" },
  ],
  graph: [
    ["Actor_Synthetic_001", "Persona_Synthetic_001", "PERSONA_RELATIONSHIP", 0.92],
    ["Persona_Synthetic_001", "PGP_MOCK_001", "SHARED_PGP", 0.88],
    ["Actor_Synthetic_002", "Wallet_Mock_001", "WALLET_RELATIONSHIP", 0.72],
    ["Actor_Synthetic_001", "Infra_Mock_001", "INFRASTRUCTURE_CORRELATION", 0.56],
    ["Evidence_Mock_001", "Actor_Synthetic_001", "SUPPORTS", 0.91],
  ],
  timeline: [
    { date: "2025-01-14", label: "Persona_Synthetic_001 appears on Forum_A", kind: "activity" },
    { date: "2025-02-03", label: "Stylometric signal crosses review threshold", kind: "evidence" },
    { date: "2025-02-18", label: "PGP_MOCK_001 observed on Market_B", kind: "link" },
    { date: "2025-03-01", label: "Conflicting timestamp detected", kind: "conflict" },
  ],
  scenarios: {
    high: { label: "High Confidence Match", description: "Multi-signal alignment", confidence: 0.91, nEff: 4.2, cas: "SUPPORTED", coverage: "95%", warning: "Stable across signal removal." },
    decoy: { label: "Decoy / False-Link Attack", description: "High correlation, low independence", confidence: 0.48, nEff: 1.7, cas: "ABSTAIN", coverage: "95%", warning: "Dependence-stratified calibration is unstable." },
    insufficient: { label: "Insufficient Signal", description: "Automatic abstention", confidence: 0.19, nEff: 0.9, cas: "ABSTAIN", coverage: "95%", warning: "N_eff below the minimum sufficiency threshold." },
  },
};

const featureGroups = [
  { code: "A", title: "Evidence Intelligence", tab: "evidence", items: [] },
  { code: "B", title: "Attribution & Identity", tab: "attribution", items: [] },
  { code: "C", title: "AI Persona Intelligence", tab: "persona", items: [] },
  { code: "D", title: "Attribution Reliability", tab: "reliability", items: [] },
  { code: "E", title: "Investigator Intelligence", tab: "reporting", items: [] },
];

const cls = (...values) => values.filter(Boolean).join(" ");
const pct = (value) => `${Math.round(value * 100)}%`;

function Card({ title, eyebrow, children, className = "" }) {
  return <section className={cls("rounded-lg border border-[#d9e1df] bg-white p-5 shadow-[0_10px_30px_rgba(37,50,42,0.07)]", className)}>
    <div className="mb-4 flex items-start justify-between gap-4"><div>{eyebrow && <p className="mb-1 font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-[#b24a31]">{eyebrow}</p>}<h2 className="font-serif text-lg text-[#172126]">{title}</h2></div></div>
    {children}
  </section>;
}

function Meter({ value, color = "bg-[#2e6b59]" }) {
  return <div className="h-2 overflow-hidden rounded-full bg-[#e7ece8]"><div className={cls("h-full rounded-full transition-all duration-300", color)} style={{ width: `${Math.min(100, value * 100)}%` }} /></div>;
}

function Pill({ children, tone = "neutral" }) {
  const tones = { neutral: "bg-[#eef2ef] text-[#53615e]", green: "bg-[#e2f0e8] text-[#2e6b59]", red: "bg-[#f5e2dc] text-[#9d3e29]", amber: "bg-[#f5ecd6] text-[#8b681d]" };
  return <span className={cls("inline-flex items-center px-2 py-1 font-mono text-[10px] font-bold uppercase tracking-wide", tones[tone])}>{children}</span>;
}

function Stat({ label, value, detail }) {
  return <div className="border-l-2 border-[#d9e1df] pl-3"><strong className="block font-serif text-2xl text-[#172126]">{value}</strong><span className="block font-mono text-[10px] uppercase tracking-wide text-[#657277]">{label}</span>{detail && <span className="mt-1 block text-xs text-[#657277]">{detail}</span>}</div>;
}

function EvidenceRows({ evidence, selected, onToggle }) {
  return <div className="divide-y divide-[#edf0ed]">{evidence.map((item) => <label key={item.id} className="flex cursor-pointer items-start gap-3 py-3">
    <input type="checkbox" checked={selected[item.id] !== false} onChange={() => onToggle(item.id)} className="mt-1 accent-[#b24a31]" />
    <span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><strong className="text-sm text-[#172126]">{item.kind}</strong><Pill tone={item.status === "conflicting" ? "red" : item.status === "redundant" ? "amber" : "green"}>{item.status}</Pill></span><span className="mt-1 block text-xs text-[#657277]">{item.id} / {item.source} / {item.note}</span></span>
    <span className="font-mono text-xs text-[#2e6b59]">{pct(item.strength)}</span>
  </label>)}</div>;
}

const graphNodes = [
  { id: "Actor_Synthetic_001", type: "ACTOR", x: "50%", y: "50%", tone: "core", evidence: ["Evidence_Mock_001", "Evidence_Mock_002", "Evidence_Mock_004"] },
  { id: "Handle_northstar_mock", type: "HANDLE", x: "17%", y: "27%", tone: "green", evidence: ["Evidence_Mock_001"] },
  { id: "PGP_MOCK_001", type: "PGP", x: "50%", y: "13%", tone: "amber", evidence: ["Evidence_Mock_002"] },
  { id: "Wallet_Mock_001", type: "WALLET", x: "83%", y: "27%", tone: "green", evidence: ["Evidence_Mock_003"] },
  { id: "Market_A", type: "MARKETPLACE", x: "20%", y: "77%", tone: "blue", evidence: ["Evidence_Mock_001"] },
  { id: "Forum_A", type: "FORUM", x: "80%", y: "77%", tone: "blue", evidence: ["Evidence_Mock_004", "Evidence_Mock_005"] },
];

function ProvenanceChain({ evidence }) {
  const item = evidence[0];
  const steps = [
    ["Evidence", item.id], ["Source", item.source], ["Collection time", "2025-03-04 09:00 UTC"],
    ["Evidence type", item.kind], ["Related actor", item.supports], ["Confidence contribution", pct(item.strength)],
  ];
  return <div className="grid gap-2 sm:grid-cols-6">{steps.map(([label, value], index) => <div key={label} className="relative border border-[#2b4a55] bg-[#102632] p-3 after:absolute after:right-[-9px] after:top-1/2 after:hidden after:h-px after:w-4 after:bg-[#e0a33a] sm:after:block"><span className="block font-mono text-[9px] uppercase tracking-widest text-[#7fa2ad]">0{index + 1} / {label}</span><strong className="mt-2 block break-words text-xs text-[#edf6f5]">{value}</strong></div>)}</div>;
}

function RelationshipGraph({ selectedNode, onSelect, anonymized }) {
  return <div className="grid gap-4 lg:grid-cols-[1.6fr_1fr]"><div className="relative min-h-[360px] overflow-hidden border border-[#2b4a55] bg-[#091923]" style={{ backgroundImage: "linear-gradient(#17323d 1px, transparent 1px), linear-gradient(90deg, #17323d 1px, transparent 1px)", backgroundSize: "36px 36px" }}><svg className="pointer-events-none absolute inset-0 h-full w-full" preserveAspectRatio="none"><line x1="50%" y1="50%" x2="17%" y2="27%" stroke="#4a7b82" strokeWidth="1" strokeDasharray="5 4" /><line x1="50%" y1="50%" x2="50%" y2="13%" stroke="#e0a33a" strokeWidth="1.5" /><line x1="50%" y1="50%" x2="83%" y2="27%" stroke="#4a7b82" strokeWidth="1" strokeDasharray="5 4" /><line x1="50%" y1="50%" x2="20%" y2="77%" stroke="#3a6872" strokeWidth="1" /><line x1="50%" y1="50%" x2="80%" y2="77%" stroke="#b8584a" strokeWidth="1.5" strokeDasharray="4 3" /></svg>{graphNodes.map((node) => <button key={node.id} onClick={() => onSelect(node)} className={cls("absolute z-10 -translate-x-1/2 -translate-y-1/2 border px-3 py-2 text-left transition hover:scale-105", node.tone === "core" ? "border-[#e0a33a] bg-[#b87924] text-white" : node.tone === "amber" ? "border-[#e0a33a] bg-[#172f38] text-[#f4cb7d]" : node.tone === "green" ? "border-[#5d9e89] bg-[#12383a] text-[#b9e2d1]" : node.tone === "blue" ? "border-[#4c8793] bg-[#102d38] text-[#b8dce2]" : "border-[#b8584a] bg-[#3d2024] text-[#f2b5aa]", selectedNode?.id === node.id && "ring-2 ring-white ring-offset-2 ring-offset-[#091923]")} style={{ left: node.x, top: node.y }}><span className="block font-mono text-[9px] uppercase tracking-widest opacity-70">{node.type}</span><strong className="block max-w-[130px] truncate text-xs">{anonymized ? "[REDACTED]" : node.id}</strong></button>)}</div><div className="border border-[#2b4a55] bg-[#102632] p-4 text-[#d8e8e8]"><p className="font-mono text-[10px] uppercase tracking-widest text-[#e0a33a]">Node inspection</p>{selectedNode ? <><h3 className="mt-3 font-serif text-xl text-white">{anonymized ? "[REDACTED NODE]" : selectedNode.id}</h3><p className="mt-1 font-mono text-[10px] uppercase text-[#7fa2ad]">{selectedNode.type} / synthetic relationship node</p><div className="mt-5"><p className="mb-2 text-xs text-[#9bb8bd]">Supporting evidence</p>{selectedNode.evidence.map((id) => <div key={id} className="mb-2 border-l-2 border-[#e0a33a] bg-[#0b202b] px-3 py-2 font-mono text-xs">{id}</div>)}</div><p className="mt-5 text-xs leading-5 text-[#9bb8bd]">Click another node to inspect its supporting trail. Shared edges are candidate relationships only.</p></> : <p className="mt-5 text-sm leading-6 text-[#9bb8bd]">Select a node to reveal its supporting evidence IDs and synthetic relationship context.</p>}</div></div>;
}

function ContradictionEngine() {
  return <div className="grid gap-4 md:grid-cols-3"><div className="border border-[#5d9e89] bg-[#102f31] p-4"><p className="font-mono text-[10px] uppercase tracking-widest text-[#8fcbb6]">Supporting</p><strong className="mt-2 block font-serif text-2xl text-white">3 signals</strong><p className="mt-2 text-xs text-[#a8c8c5]">Stylometry, PGP, behavior</p></div><div className="border border-[#b8584a] bg-[#3a2025] p-4"><p className="font-mono text-[10px] uppercase tracking-widest text-[#f0a99d]">Contradictory</p><strong className="mt-2 block font-serif text-2xl text-white">1 signal</strong><p className="mt-2 text-xs text-[#dbb3ad]">Conflicting synthetic timestamp</p></div><div className="border border-[#e0a33a] bg-[#352b1b] p-4"><p className="font-mono text-[10px] uppercase tracking-widest text-[#f4cb7d]">Assessment</p><strong className="mt-2 block font-serif text-2xl text-white">REVIEW</strong><p className="mt-2 text-xs text-[#d6c29a]">Candidate link, not identity proof</p></div></div>;
}

function AttributionMatrix() {
  const rows = [["Stylometry", "0.82", "Independent", "+0.18"], ["PGP relationship", "0.88", "Dependent", "+0.16"], ["Wallet pattern", "0.72", "Dependent", "+0.09"], ["Timestamp conflict", "0.63", "Independent", "-0.07"], ["Infrastructure", "0.56", "Redundant", "+0.03"]];
  return <div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-xs"><thead className="font-mono uppercase tracking-widest text-[#7fa2ad]"><tr><th className="pb-3">Signal</th><th className="pb-3">Strength</th><th className="pb-3">Dependence</th><th className="pb-3">Contribution</th><th className="pb-3">Decision use</th></tr></thead><tbody>{rows.map(([signal, strength, dependence, contribution]) => <tr key={signal} className="border-t border-[#2b4a55]"><td className="py-3 font-semibold text-[#edf6f5]">{signal}</td><td className="font-mono text-[#9fd0c0]">{strength}</td><td className="text-[#9bb8bd]">{dependence}</td><td className={contribution.startsWith("-") ? "font-mono text-[#ef9f91]" : "font-mono text-[#9fd0c0]"}>{contribution}</td><td className="text-[#9bb8bd]">candidate relationship</td></tr>)}</tbody></table></div>;
}

export default function InvestigatorConsole() {
  const [activeTab, setActiveTab] = useState("overview");
  const [activeFeature, setActiveFeature] = useState("Overview");
  const [openModule, setOpenModule] = useState("A");
  const [scenarioKey, setScenarioKey] = useState("high");
  const [noise, setNoise] = useState(0);
  const [anonymized, setAnonymized] = useState(false);
  const [selectedGraphNode, setSelectedGraphNode] = useState(null);
  const [selectedEvidence, setSelectedEvidence] = useState(() => Object.fromEntries(SYNTHETIC_STATE.evidence.map((item) => [item.id, true])));
  const [audit, setAudit] = useState([{ id: "Audit_Mock_001", action: "investigation_started", time: "2025-03-04T09:00:00Z" }]);

  const scenario = SYNTHETIC_STATE.scenarios[scenarioKey];
  const selected = SYNTHETIC_STATE.evidence.filter((item) => selectedEvidence[item.id] !== false);
  const recalculated = useMemo(() => {
    const raw = selected.length;
    const groups = new Set(selected.map((item) => item.group));
    const conflictPenalty = selected.filter((item) => item.status === "conflicting").length * 0.07;
    const noisePenalty = noise / 180;
    const confidence = Math.max(0, Math.min(0.99, scenario.confidence - (SYNTHETIC_STATE.evidence.length - raw) * 0.11 - conflictPenalty - noisePenalty));
    const nEff = Math.max(0, Math.min(5, groups.size - selected.filter((item) => item.status === "redundant").length * 0.45 - noise / 45));
    const status = confidence >= 0.68 && nEff >= 3 ? "SUPPORTED" : "ABSTAIN";
    return { raw, groups: groups.size, confidence, nEff, status };
  }, [selected, noise, scenario]);
  const identifier = (value) => anonymized ? "[REDACTED_ACTOR]" : value;
  const addAudit = (action) => setAudit((items) => [{ id: `Audit_Mock_${String(items.length + 1).padStart(3, "0")}`, action, time: "2025-03-04T09:00:00Z" }, ...items]);
  const toggleEvidence = (id) => { setSelectedEvidence((current) => ({ ...current, [id]: current[id] === false })); addAudit("evidence_counterfactual_changed"); };

  const metrics = [
    ["Actors", 12], ["Personas", 12], ["Evidence", selected.length], ["Relationships", 5],
    ["Sources", 4], ["Conflicting evidence", selected.filter((item) => item.status === "conflicting").length], ["Candidate links", 2], ["Abstentions", recalculated.status === "ABSTAIN" ? 1 : 0],
  ];

  const selectFeature = (tab, feature, code) => { setActiveTab(tab); setActiveFeature(feature); setOpenModule(code); addAudit(`feature_${feature.toLowerCase().replaceAll(" ", "_")}`); };

  const renderOverview = () => <div className="grid gap-5 xl:grid-cols-[1.45fr_1fr]">
    <Card title="CAS control room" eyebrow="Current synthetic hypothesis">
      <div className="grid gap-5 md:grid-cols-[1fr_1.3fr]"><div><p className="mb-1 font-mono text-[10px] uppercase tracking-wide text-[#657277]">Attribution status</p><div className="flex items-center gap-3"><span className="font-serif text-4xl text-[#172126]">{recalculated.status}</span><Pill tone={recalculated.status === "SUPPORTED" ? "green" : "red"}>{scenario.coverage} bounds</Pill></div><p className="mt-3 text-sm text-[#657277]">{scenario.description}. This is a synthetic attribution hypothesis, not an identity conclusion.</p></div><div className="space-y-4"><div className="flex justify-between text-xs"><span>Confidence decomposition</span><strong>{pct(recalculated.confidence)}</strong></div><Meter value={recalculated.confidence} color={recalculated.status === "SUPPORTED" ? "bg-[#2e6b59]" : "bg-[#b24a31]"} /><div className="grid grid-cols-3 gap-3 text-xs"><Stat label="Evidence" value="31%" /><Stat label="PGP / wallet" value="24%" /><Stat label="Behavior" value="18%" /></div></div></div>
    </Card>
    <Card title="Why CAS abstained?" eyebrow="Deterministic explanation"><div className="border-l-2 border-[#b24a31] bg-[#fbf3ef] p-4 text-sm text-[#53615e]"><strong className="mb-2 block font-mono text-xs uppercase text-[#9d3e29]">{recalculated.status === "ABSTAIN" ? "ATTRIBUTION ABSTAINED" : "ATTRIBUTION SET RETAINED"}</strong><ul className="space-y-2">{(recalculated.status === "ABSTAIN" ? [recalculated.nEff < 3 ? "N_eff below 3.0 threshold" : null, noise > 35 ? "Adversarial noise exceeds stability threshold" : null, selected.some((item) => item.status === "conflicting") ? "Conflicting evidence detected" : null].filter(Boolean) : ["Independent evidence exceeds sufficiency threshold", "No decisive conflict after selected signals"]).map((reason) => <li key={reason}>- {reason}</li>)}</ul></div></Card>
    <Card title="Evidence sufficiency" eyebrow="Counterfactual simulator" className="xl:col-span-2"><div className="grid gap-5 lg:grid-cols-[1fr_1fr_1.2fr]"><div><div className="mb-2 flex justify-between text-xs"><span>Effective independent evidence</span><strong>{recalculated.nEff.toFixed(1)} / 5.0</strong></div><Meter value={recalculated.nEff / 5} color="bg-[#2e6b59]" /><div className="mt-3 flex justify-between text-xs text-[#657277]"><span>{recalculated.raw} raw records</span><span>{recalculated.groups} signal groups</span></div></div><div><p className="mb-2 font-mono text-[10px] uppercase tracking-wide text-[#657277]">Remove signals to test sufficiency</p><EvidenceRows evidence={SYNTHETIC_STATE.evidence.slice(0, 4)} selected={selectedEvidence} onToggle={toggleEvidence} /></div><div className="grid gap-3 sm:grid-cols-2"><div className="border border-[#d9e1df] p-4"><p className="font-mono text-[10px] uppercase text-[#657277]">All evidence</p><strong className="font-serif text-2xl">{pct(scenario.confidence)}</strong><p className="text-xs text-[#657277]">Baseline confidence</p></div><div className="border border-[#d9e1df] p-4"><p className="font-mono text-[10px] uppercase text-[#657277]">Current selection</p><strong className="font-serif text-2xl">{pct(recalculated.confidence)}</strong><p className="text-xs text-[#657277]">Recalculated locally</p></div></div></div></Card>
  </div>;

  const renderEvidence = () => <div className="space-y-5"><Card title="Evidence provenance chain" eyebrow="Why did the system connect these identities?"><ProvenanceChain evidence={SYNTHETIC_STATE.evidence} /></Card><div className="grid gap-5 xl:grid-cols-[1.25fr_1fr]"><Card title="Evidence provenance ledger" eyebrow="Trace every signal"><EvidenceRows evidence={SYNTHETIC_STATE.evidence} selected={selectedEvidence} onToggle={toggleEvidence} /></Card><div className="space-y-5"><Card title="Source reliability" eyebrow="Explainable synthetic scores">{SYNTHETIC_STATE.sources.map((source) => <div key={source.id} className="mb-4 last:mb-0"><div className="flex justify-between text-sm"><span>{source.id}</span><strong>{pct(source.reliability)}</strong></div><Meter value={source.reliability} /><p className="mt-1 text-xs text-[#657277]">{source.lineage} / error rate {pct(source.errorRate)} / {source.independence}</p></div>)}</Card><Card title="Correlation and redundancy" eyebrow="Common-source detection"><div className="space-y-3 text-sm">{[["Source_Mock_Beta", "2 evidence records", "dependent"], ["shared-infra", "Actor 001 + Actor 002", "common source"], ["timeline-conflict", "1 contradiction", "review"]].map(([label, value, tone]) => <div key={label} className="flex items-center justify-between border-b border-[#edf0ed] pb-3"><span><strong className="block">{label}</strong><span className="text-xs text-[#657277]">{value}</span></span><Pill tone={tone === "review" ? "red" : "amber"}>{tone}</Pill></div>)}</div></Card></div></div><Card title="False-link / contradiction engine" eyebrow="Supporting evidence + evidence suggesting they are not the same"><ContradictionEngine /></Card></div>;

  const renderAttribution = () => <div className="grid gap-5 lg:grid-cols-2"><Card title="Cross-marketplace matcher" eyebrow="Candidate identity links"><div className="grid grid-cols-2 gap-3"><div className="border border-[#d9e1df] p-4"><p className="font-mono text-[10px] text-[#657277]">CANDIDATE A</p><strong>{identifier("Actor_Synthetic_001")}</strong><p className="mt-2 text-xs text-[#657277]">Forum_A / Market_A<br />northstar_mock</p></div><div className="border border-[#d9e1df] p-4"><p className="font-mono text-[10px] text-[#657277]">CANDIDATE B</p><strong>{identifier("Actor_Synthetic_002")}</strong><p className="mt-2 text-xs text-[#657277]">Market_B<br />northstar_alt</p></div></div><div className="mt-4 flex items-center justify-between"><span className="text-sm text-[#657277]">Supporting signals: PGP, wallet, stylometry</span><Pill tone="amber">POSSIBLE_IDENTITY_LINK</Pill></div></Card><Card title="PGP and wallet relationships" eyebrow="Synthetic relationship graph"><div className="space-y-3 font-mono text-xs"><div className="flex items-center gap-3"><span className="bg-[#e2f0e8] px-3 py-2">PGP_MOCK_001</span><span className="text-[#b24a31]">connects</span><span className="bg-[#eef2ef] px-3 py-2">Persona_001 + Persona_002</span></div><div className="flex items-center gap-3"><span className="bg-[#e2f0e8] px-3 py-2">Wallet_Mock_001</span><span className="text-[#b24a31]">pattern</span><span className="bg-[#eef2ef] px-3 py-2">Market_A -&gt; Market_B</span></div></div></Card><Card title="Infrastructure fingerprinting" eyebrow="No Tor or network access" className="lg:col-span-2"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="font-mono uppercase text-[#657277]"><tr><th className="pb-3">Synthetic node</th><th className="pb-3">SSH hash</th><th className="pb-3">TLS pattern</th><th className="pb-3">Match</th><th className="pb-3">Status</th></tr></thead><tbody>{[["Infra_Mock_001", "ssh-mock-a1", "tls-pattern-7", "82%", "candidate"], ["Infra_Mock_002", "ssh-mock-a1", "tls-pattern-9", "56%", "decoy"]].map((row) => <tr key={row[0]} className="border-t border-[#edf0ed]"><td className="py-3 font-semibold">{row[0]}</td><td>{row[1]}</td><td>{row[2]}</td><td className="font-mono text-[#2e6b59]">{row[3]}</td><td><Pill tone={row[4] === "decoy" ? "red" : "green"}>{row[4]}</Pill></td></tr>)}</tbody></table></div></Card></div>;

  const renderPersona = () => <div className="grid gap-5 lg:grid-cols-2"><Card title="Stylometric fingerprint" eyebrow="Synthetic writing comparison"><div className="space-y-4">{[["Vocabulary overlap", 0.82], ["Sentence rhythm", 0.76], ["Punctuation pattern", 0.69], ["Character n-grams", 0.88]].map(([label, value]) => <div key={label}><div className="mb-1 flex justify-between text-sm"><span>{label}</span><strong>{pct(value)}</strong></div><Meter value={value} /></div>)}</div><p className="mt-4 text-xs text-[#657277]">Similarity is between fictional personas only; it does not identify a real person.</p></Card><Card title="Behavioral fingerprint" eyebrow="Synthetic activity vector"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[["active hours", "21:00-01:00"], ["active days", "Tue / Fri"], ["frequency", "4.2 / wk"], ["platforms", "3"]].map(([label, value]) => <div key={label} className="border border-[#d9e1df] p-3"><strong className="block text-sm">{value}</strong><span className="text-[10px] uppercase text-[#657277]">{label}</span></div>)}</div></Card><Card title="Persona evolution timeline" eyebrow="Migration and rebranding" className="lg:col-span-2"><div className="relative ml-3 border-l border-[#d9e1df] pl-6">{SYNTHETIC_STATE.timeline.map((event) => <div key={event.date} className="relative mb-5 last:mb-0"><span className="absolute -left-[31px] top-1 h-2 w-2 rounded-full bg-[#b24a31]" /><time className="font-mono text-[10px] text-[#b24a31]">{event.date}</time><p className="mb-0 text-sm">{event.label}</p></div>)}</div></Card></div>;

  const renderReliability = () => <div className="grid gap-5 lg:grid-cols-2"><Card title="Dependence-stratified calibration" eyebrow="Synthetic evaluation"><div className="grid grid-cols-3 gap-4 text-center">{[["Independent", "0.94", "green"], ["Dependent", "0.61", "amber"], ["Redundant", "0.42", "red"]].map(([label, value, tone]) => <div key={label}><div className={cls("mx-auto mb-2 flex h-20 w-20 items-center justify-center rounded-full border-8 text-xl font-semibold", tone === "green" ? "border-[#b5d8c2] text-[#2e6b59]" : tone === "amber" ? "border-[#e8d9a8] text-[#8b681d]" : "border-[#e8beb2] text-[#9d3e29]")}>{value}</div><p className="mb-0 text-xs">{label}</p></div>)}</div><div className="mt-5 bg-[#fbf3ef] p-3 text-xs text-[#9d3e29]">Warning: small evidence changes materially affect the candidate set under the current decoy scenario.</div></Card><Card title="LOSO fragility analysis" eyebrow="Remove one signal at a time">{[["PGP relationship", 0.18], ["Stylometry", 0.11], ["Wallet", 0.08], ["Behavior", 0.05]].map(([label, value]) => <div key={label} className="mb-4 last:mb-0"><div className="mb-1 flex justify-between text-sm"><span>{label}</span><strong>-{pct(value)}</strong></div><Meter value={value} color="bg-[#b24a31]" /></div>)}</Card><Card title="Adversarial stress testing" eyebrow="Synthetic decoy evaluation"><div className="flex items-center justify-between border-b border-[#edf0ed] py-3"><span>Misleading handle similarity</span><Pill tone="red">detected</Pill></div><div className="flex items-center justify-between border-b border-[#edf0ed] py-3"><span>Duplicated evidence</span><Pill tone="amber">discounted</Pill></div><div className="flex items-center justify-between py-3"><span>Conflicting timestamp</span><Pill tone="red">abstain</Pill></div></Card><Card title="Selective accuracy" eyebrow="Synthetic cases only"><div className="grid grid-cols-3 gap-3 text-center"><Stat label="Supported" value="1" /><Stat label="Uncertain" value="1" /><Stat label="Abstained" value="1" /></div><p className="mt-4 text-xs text-[#657277]">No real-world performance claim. Metrics are limited to embedded mock cases.</p></Card></div>;

  const renderReporting = () => <div className="grid gap-5 xl:grid-cols-[1fr_1.2fr]"><Card title="Timeline investigation" eyebrow="Synchronized synthetic events"><div className="space-y-3">{SYNTHETIC_STATE.timeline.map((event) => <div key={event.date} className="flex gap-4 border-b border-[#edf0ed] pb-3 last:border-0"><time className="w-24 shrink-0 font-mono text-xs text-[#b24a31]">{event.date}</time><span className="text-sm">{event.label}</span></div>)}</div></Card><Card title="Interactive relationship graph" eyebrow="Click-free review view"><div className="grid gap-3 sm:grid-cols-2">{SYNTHETIC_STATE.graph.map(([from, to, type, strength]) => <div key={`${from}-${to}`} className="border border-[#d9e1df] p-3"><div className="flex items-center justify-between gap-2 text-xs"><span className="truncate font-semibold">{identifier(from)}</span><span className="text-[#b24a31]">-&gt;</span><span className="truncate">{identifier(to)}</span></div><div className="mt-2 flex justify-between font-mono text-[10px] text-[#657277]"><span>{type}</span><strong>{pct(strength)}</strong></div></div>)}</div></Card><Card title="Reproducible audit trail" eyebrow="Deterministic actions" className="xl:col-span-2"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="font-mono uppercase text-[#657277]"><tr><th className="pb-2">Event</th><th className="pb-2">Action</th><th className="pb-2">Timestamp</th></tr></thead><tbody>{audit.map((event) => <tr key={event.id} className="border-t border-[#edf0ed]"><td className="py-3 font-mono">{event.id}</td><td>{event.action}</td><td className="font-mono text-[#657277]">{event.time}</td></tr>)}</tbody></table></div></Card><Card title="Report generator" eyebrow="Local exports" className="xl:col-span-2"><div className="flex flex-wrap gap-3"><button onClick={() => addAudit("report_export_json")} className="border border-[#172126] px-4 py-2 font-mono text-xs hover:bg-[#172126] hover:text-white">Download JSON</button><button onClick={() => addAudit("report_export_csv")} className="border border-[#172126] px-4 py-2 font-mono text-xs hover:bg-[#172126] hover:text-white">Download CSV</button><button onClick={() => addAudit("report_export_pdf")} className="border border-[#172126] px-4 py-2 font-mono text-xs hover:bg-[#172126] hover:text-white">Download PDF</button></div><p className="mt-3 text-xs text-[#657277]">Exports are local demo actions and contain synthetic records only.</p></Card></div>;

  const renderInvestigator = () => <div className="space-y-5"><Card title="Actor Relationship Graph 2.0" eyebrow="Interactive temporal synthetic graph"><RelationshipGraph selectedNode={selectedGraphNode} onSelect={setSelectedGraphNode} anonymized={anonymized} /></Card><Card title="Attribution evidence matrix" eyebrow="Transparent confidence contribution"><AttributionMatrix /></Card>{renderReporting()}</div>;
  const content = activeTab === "overview" ? renderOverview() : { evidence: renderEvidence, attribution: renderAttribution, persona: renderPersona, reliability: renderReliability, reporting: renderInvestigator }[activeTab]();
  return <div className="min-h-screen bg-[radial-gradient(circle_at_90%_0%,#183d49_0,transparent_34%),#08141b] font-serif text-[#edf6f5]">
    <header className="mx-auto max-w-[1440px] px-5 pb-5 pt-8 sm:px-8"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="mb-2 font-mono text-[10px] font-bold uppercase tracking-[0.18em] text-[#b24a31]">Local / offline / synthetic</p><h1 className="text-4xl leading-none tracking-[-0.04em] sm:text-6xl">Investigator Console</h1></div><div className="flex flex-wrap items-center gap-3"><label className="flex items-center gap-2 text-xs"><span>Scenario</span><select value={scenarioKey} onChange={(event) => { setScenarioKey(event.target.value); addAudit("scenario_changed"); }} className="border border-[#d9e1df] bg-white px-3 py-2 font-mono text-xs"><option value="high">High Confidence Match</option><option value="decoy">Decoy / False-Link Attack</option><option value="insufficient">Insufficient Signal</option></select></label><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={anonymized} onChange={(event) => { setAnonymized(event.target.checked); addAudit("anonymizer_changed"); }} className="accent-[#b24a31]" /> Anonymize</label></div></div><div className="mt-6 bg-[#172126] px-4 py-3 text-sm text-[#edf1ea]">Synthetic demonstration data. Candidate relationships are analytical hypotheses, never proof of a person's identity.</div></header>
    <main className="mx-auto max-w-[1440px] px-5 pb-12 sm:px-8"><div className="grid gap-6 lg:grid-cols-[280px_1fr]"><aside className="h-fit border border-[#2b4a55] bg-[#102632] p-4 shadow-[0_10px_30px_rgba(0,0,0,0.22)] lg:sticky lg:top-5"><p className="mb-3 font-mono text-[10px] font-bold uppercase tracking-[0.16em] text-[#7fa2ad]">Intelligence modules</p><button onClick={() => selectFeature("overview", "Overview", "overview")} className={cls("mb-3 w-full border-l-2 px-3 py-2 text-left text-sm", activeTab === "overview" ? "border-[#e0a33a] bg-[#352b1b] text-[#f4cb7d]" : "border-transparent text-[#9bb8bd]")}>Overview</button>{featureGroups.map((group) => <div key={group.code} className="mb-4"><button onClick={() => setOpenModule(openModule === group.code ? null : group.code)} className="mb-1 flex w-full items-center gap-2 text-left"><span className="flex h-5 w-5 items-center justify-center bg-[#e0a33a] font-mono text-[10px] text-[#172126]">{group.code}</span><span className="font-mono text-[10px] font-bold uppercase tracking-wide text-[#edf6f5]">{group.title}</span><span className="ml-auto text-[#7fa2ad]">{openModule === group.code ? "-" : "+"}</span></button>{openModule === group.code && <div className="space-y-0.5 pl-7">{group.items.map((feature) => <button key={feature} onClick={() => selectFeature(group.tab, feature, group.code)} className={cls("block w-full border-l px-2 py-1.5 text-left text-xs leading-snug", activeFeature === feature ? "border-[#e0a33a] bg-[#352b1b] text-[#f4cb7d]" : "border-transparent text-[#9bb8bd] hover:text-white")}>{feature}</button>)}</div>}</div>)}</aside><section><div className="mb-3 flex items-center justify-between gap-4"><p className="mb-0 text-sm text-[#9bb8bd]">Selected feature: <strong className="text-[#f4cb7d]">{activeFeature}</strong></p><label className="flex min-w-[240px] items-center gap-3 text-xs text-[#9bb8bd]">Noise <input type="range" min="0" max="100" value={noise} onChange={(event) => setNoise(Number(event.target.value))} className="accent-[#e0a33a]" /><strong className="w-10 font-mono text-[#f4cb7d]">{noise}%</strong></label></div><div className="mb-5 grid grid-cols-2 gap-3 sm:grid-cols-4 xl:grid-cols-8">{metrics.map(([label, value]) => <div key={label} className="border border-[#2b4a55] bg-[#102632] p-3"><strong className="block font-serif text-2xl text-white">{value}</strong><span className="font-mono text-[9px] uppercase tracking-wide text-[#7fa2ad]">{label}</span></div>)}</div>{content}</section></div></main>
  </div>;
}
